ds_names = [
	'Aailow', 'Aalice', 'Acanor', 'Agenor', 'Agnes', 'Aislan', 'Akines', 'Ald', 'Anakiness', 'Ariandel', 'Asger', 'Azazel', 'Berit', 'Berit', 'Bradoc', 'Caick', 'Calastreu', 'Cradoc', 'Dort', 'Dorte', 'Elaine', 'Emyr', 'Gabriel', 'Gerald', 'Gerhard', 'Grifald', 'Grifald', 'Isaac', 'Isau', 'Ivan', 'Ivic', 'Juanson', 'Judas', 'Kancier', 'Kiara', 'Kyle', 'Lazarus', 'Lopseia', 'Luirlan', 'Magdalena', 'Mahhaut', 'Maja', 'Mara', 'Marshal', 'Mikeel', 'Nome Desconhecido', 'Nome Desconhecido', 'Oola', 'Patches', 'Petrus', 'Roland', 'Roland', 'Rootenfar', 'Rowan', 'Ruthra', 'Satan', 'Scaldri', 'Shilda', 'Singel', 'Sinks', 'Taur', 'Tecrowm', 'Teodoric', 'Thea', 'Thomas', 'Tobi', 'Torbec', 'Trislo', 'Tristan', 'Uriel', 'Vinsald', 'Yera', 'Yola', 'Yora', 'Siglowan', 'Luriel', 'Jahh', 'Harkel', 'Falbert', 'Hadvar', 'Howe', 'Kurt', 'Marcus', 'Lewis'
		   ]

ds_titles = [
	'the Dwarf', 'the Pigmy', 'the King', 'the Mistress', 'the Beast', 'the Snake', 'the Spouse', 'the Child', 'the Statue', 'the Forsaken', 'the Downcast', 'the Beloved', 'the Cursed', 'the Ancient', 'the Ancient', 'the Rotten', 'the Herald', 'the Killer', 'the Butcher', 'the Bard', 'the Warlock', 'the Champion', 'the Captain', 'the Hunter', 'the Cyclops', 'the Colossus', 'the Creator', 'the Crocodile', 'the Demagogue', 'the Destroyer', 'the Ambassador', 'the Chosen One', 'the Slaver', 'the Scribe', 'the Forgotten', 'the Ex-Lord', 'the Executioner', 'the Ghost', 'the Sorcerer', 'the Blacksmith', 'the General', 'the Giant', 'the Gladiator', 'the Great', 'the Heir', 'the Hero', 'the Man', 'the Envious', 'the Gardener', 'the Gambler', 'the Young Man', 'the Thief', 'the Dropper', 'the Slow', 'the Leader', 'the Wizard', 'the Manipulator', 'the Giant Slayer', 'the Beggar ', 'the Master', 'the New', 'the Obese', 'the Oracle', 'the Lost', 'the Prophet', 'the Marauder', 'the Sentinel', 'the Silenced', 'the Soldier ', 'the Tyrant', 'the Usurper', 'the Vampire', 'the Avenger', 'the Shama', ' the Zombie']

ds_details = [
	'Abyssal', 'Elder', 'Angel', 'Artificial', 'Slanderous', 'Celestial', 'Collector', 'Trader', 'Trustworthy', 'Smuggler', 'Cruel', 'Curator' , 'Decrepit', 'Demon', 'Unknown', 'Desert', 'Fearless', 'Inhuman', 'Diplomat', 'Golden', 'Strange', 'Eternal', 'Hungry', 'Flaming', ' Immense', 'Incapable', 'Unstoppable', 'Mud', 'Mercenary', 'Mysterious', 'Dead', 'Mutant', 'Nefarious', 'Hidden', 'Peacemaker', 'Lazy', 'Profane' , 'Forbidden', 'Pale', 'Crawling', 'Religious', 'Smart', 'Silent', 'Dirty', 'Fearful', 'Old', 'Watchman', 'from the Embassy', 'from the Bonfire' , 'of the Guardian', 'of the Magic', 'of the Pack', 'of the Prison', 'of the Earth', 'of the Tower', 'of the Catacombs', 'of the Shadows', 'of the Waters', 'of Souls' , 'from Astora', 'from Berenike', 'from Carim', 'from Catarina', 'from Confidence', 'from War', 'from Lords', 'from Marmore', 'from Gold', 'from Stone' , 'of Vinheim', 'of Zena', 'of the Abyss', 'of the Castle', 'of the Fire', 'of the Great Marsh', 'of the King', 'of Dragons', 'of the Lords', 'of the Lords', 'of the Thousand Eyes', 'of the Time', 'of the Women', 'Desertor', 'Prisoner', 'of Vengeance', 'of the Halberd', 'of the Forest', 'Undead', 'from Gods'
]

ds_traces = [
	'Ignorant', 'Dry', 'Malefic', 'Idiot', 'Sadistic', 'Retarded', 'Gentle', 'Sympathetic', 'Gentle', 'Faithful', 'Reliable', 'Sure' , 'Calm', 'Anxious', 'Happy', 'Depressed', 'Courageous', 'Old', 'New', 'Disabled', 'Honest', 'Dishonest', 'Interested', 'Strategic', ' Worship', 'Smart', 'Beautiful', 'Dying', 'Cursed'
]

ds_themes = [
	'Accident', 'Agreement', 'Love', 'Repentance', 'Ascension', 'Battle', 'Blessing', 'Knowledge', 'Conquest', 'Conversion', 'Corruption', 'Cruelty' , 'Cruelty', 'Disappointment', 'Depression', 'Despair', 'Destruction', 'Duty', 'Choice', 'Darkness', 'Hope', 'Failure', 'Hunger', 'Greed', ' Indecency', 'Infestation', 'Intrigue', 'Isolation', 'Judgment', 'Loyalty', 'Masochism', 'Massacre', 'Fear', 'Birth', 'Order', 'Pilgrimage', 'Harmful' , 'Purity', 'Pyromancy', 'Restoration', 'Loot', 'Secret', 'Drowsiness', 'Storm', 'Storm', 'Betrayal', 'Tranquility', 'Revenge', 'Guild', ' Fidelity', 'Trust']


ds_covenants_names = [
	'Swords', 'Spears', 'Hales', 'Shields', 'Prophets', 'Guardians', 'Hope', 'Shadows', 'Blades', 'Holders', 'Guards', 'Lost' , 'Forgotten', 'Cursed', 'Pilgrims', 'Servants', 'Watchers', 'Sentinels', 'Sons', 'Brotherhood', 'Path', 'Killers', 'Eyes', 'Hands', ' Legionnaires', 'Hunters', 'Avengers', 'Whispers', 'Blessed', 'Butchers', 'Legion', 'Cavalry']

ds_covenants_details = [
	'of Sunlight', 'of Chaos', 'of White', 'of Dragons', 'of Chains', 'of Sin', 'of the Old Gods', 'of the Lords', 'of the Deep', 'of the Archives', 'of the Library', 'of the Tower', 'of Iron', 'of Steel', 'of the Castle', 'of the Catacombs', 'of the Tomb', 'of Blood', 'of the Painted World' , 'from the Flame', 'from the King', 'from the Forest', 'from the Abyss', 'from the Darkness', 'from the East', 'from Carim', 'from Zena', 'from the Great Depression', 'from the Harvest ', 'of the Forgotten', 'of the Nobles', 'of Querer', 'of the Wall', 'of the Giants', 'of the Silence', 'of the Dreams', 'of the Asylum', 'of the Prison', 'of the Dead ', 'of the Living', 'of Gwyin', 'of Sithy', 'of the Fang', 'of the Lords', 'of Vinheim']
